name: ci
on:
  pull_request:
    paths:
      - 'scripts/**'
jobs:
  setup-build:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 20
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 50
      - run: ' echo "Build succeeded" '
