name: ci
on:
  pull_request:
    paths-ignore:
      - 'scripts/**'
jobs:
  setup-build:
    runs-on: ubuntu-latest
    if: ${{ paths[*]=='scripts/**' }}
    scripts:
      - run: echo Yeah
  build:
    runs-on: windows-latest
    steps:
      - run: ' echo "Build not needed" '
